language: c
compiler: gcc
before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq valac-0.30 gobject-introspection libgee-0.8

script:
  - cd src
  - make
